services:
  - type: web
    name: exam-stress-analyzer-api
    env: docker
    region: oregon
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
